name: Baato Go Client workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mock Tests
        run: |
          echo "Hello World!"
